name: nirvada_user
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  http: ^0.13.5
  image_picker: ^0.8.7
  qr_flutter: ^4.0.0
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  encrypt: ^5.0.1
  get_storage: ^2.1.1

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/logoU.png"
  android:  true
  ios: true

dev_dependencies: 
  # flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

