name: nirvada_user
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0

dev_dependencies: 
  # flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
<<<<<<< HEAD
  
  assets:
    - assets/images/
=======
  assets:
   - assets/images/

>>>>>>> 0ceb8bb141b4cce9e0be7ecfe04d913fede27c99

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

